#!/bin/bash

echo "=========================================="
echo "Apple Watch Complication Setup"
echo "=========================================="
echo ""
echo "The complication code is ready, but you need to add a WatchKit app target in Xcode."
echo ""
echo "STEPS TO FOLLOW IN XCODE:"
echo ""
echo "1. Fix App Group (if red):"
echo "   - Select TimeProgressTracker target"
echo "   - Signing & Capabilities → App Groups"
echo "   - Make sure: group.com.prabhakaran.timeprogresstracker"
echo "   - If red, register it at:"
echo "     https://developer.apple.com/account/resources/identifiers/list/applicationGroup"
echo ""
echo "2. Add WatchKit App Target:"
echo "   - File → New → Target"
echo "   - watchOS → App"
echo "   - Product Name: TimeProgressWatch"
echo "   - Bundle ID: com.prabhakaran.timeprogresstracker.watchkitapp"
echo "   - ✅ Include Complication"
echo ""
echo "3. Add Watch Widget Extension:"
echo "   - File → New → Target"
echo "   - watchOS → Widget Extension"
echo "   - Product Name: TimeProgressWatchExtension"
echo "   - Bundle ID: com.prabhakaran.timeprogresstracker.watchkitapp.watchkitextension"
echo ""
echo "4. Add Complication Code:"
echo "   - Right-click TimeProgressWatchExtension folder"
echo "   - Add Files → Select TimeProgressWatch/TimeProgressWatch.swift"
echo "   - ✅ Add to targets: TimeProgressWatchExtension"
echo ""
echo "5. Configure App Groups:"
echo "   - Select TimeProgressWatchExtension target"
echo "   - Signing & Capabilities → + Capability → App Groups"
echo "   - Add: group.com.prabhakaran.timeprogresstracker"
echo ""
echo "6. Build & Run:"
echo "   - Select TimeProgressWatch scheme"
echo "   - Run on Apple Watch simulator"
echo ""
echo "See WATCH_COMPLICATION_SETUP.md for detailed instructions."
echo ""
